=== korpling/KajukModules/documents/naehesprache.dtd
<!ELEMENT doc  (pb | line | lb | subj | praed | J | IP| Inf | KOR | FOK | VOR | SUB | obj | ADV | XX)* >
<!ATTLIST doc
        ID ID #REQUIRED
>

<!ELEMENT line  ANY>
<!ATTLIST line 
	n CDATA #REQUIRED
>

<!ELEMENT pb  ANY>
<!ATTLIST pb 
	n CDATA #IMPLIED
>
<!ENTITY % element "subj | J | FOK | VOR | SUB | IP | Inf | KOR | obj | praed | ADV | XX">

<!ELEMENT lb  (#PCDATA | %element; | lb )*>
<!ATTLIST lb 
	n CDATA #IMPLIED
	type (WR | E | subj | subjattr | obj) #IMPLIED
	ADDtype CDATA #IMPLIED
	IR (adv | disj | exp | fin | inst | kaus | kom | komp | kond | kons | konz | kop | meta | rest | temp) #IMPLIED
	ADDIR CDATA #IMPLIED
	EB (prag) #IMPLIED
>
<!ELEMENT subj  (#PCDATA) >
<!ATTLIST subj
	real  CDATA "Pron"
	type (E | noE | abs) #IMPLIED
	ADDtype CDATA #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ATTLIST praed
	real (mikro | afin) #IMPLIED
	type (E | noE) #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ELEMENT praed  (V | VP | RF | NGr | PGr | Phras | ADJGr)* >
<!ELEMENT V  (#PCDATA | HV | VV | KV | MV | HMV | FV | PV | LASSEN | TUN | AcI )* > 
<!ATTLIST V 
	ID (Fin | Inf | PII | PI |InfZU| InfAM) #REQUIRED
	type (E | noE) #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ELEMENT J  (AP | KON | SUB | AD | FOK )* >
<!ATTLIST J
	IR (adv | disj | exp | fin | inst | kaus | kom | komp | kond | kons | konz | kop | meta | rest | temp) #REQUIRED
	EB (prag) #IMPLIED
	ADDIR CDATA #IMPLIED
	norm CDATA #IMPLIED
	ID CDATA #IMPLIED
	type (E | noE | x) #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ATTLIST AP
	type (KOR | FOK | x) #IMPLIED
	ADDtype CDATA #IMPLIED
>
<!ATTLIST VOR
	type (E | noE) #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ELEMENT obj  (#PCDATA | akk | obl | prae)* >


<!ATTLIST HV
	type (E | noE) #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ATTLIST FV
	type (E | noE) #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ATTLIST Pras
	type (E | noE) #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ATTLIST VV
	type (E | noE) #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ATTLIST KV
	type (E | noE) #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ATTLIST MV
	type (E | noE) #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ATTLIST HMV
	type (E | noE) #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ATTLIST LASSEN
	type (E | noE) #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ATTLIST TUN
	type (E | noE) #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ATTLIST AcI
	type (E | noE) #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ATTLIST VP
	type (E | noE) #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ATTLIST RF
	type (E | noE) #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ATTLIST NGr
	type (E | noE) #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ATTLIST PGr
	type (E | noE) #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ATTLIST Phras
	type (E | noE) #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ATTLIST ADJGr
	type (E | noE) #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ATTLIST KON
	type (E | noE | subj | x) #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ATTLIST SUB
	type (E | noE | subj | x ) #IMPLIED
	ADDtype CDATA #IMPLIED
	ID CDATA #IMPLIED
	IR (zero) #IMPLIED
	ADDIR CDATA #IMPLIED
	norm CDATA #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ATTLIST AD
	type (x) #IMPLIED
>
<!ATTLIST FOK
	type (E | noE) #IMPLIED
	norm CDATA #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ATTLIST IP
	type (E | noE) #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ATTLIST Inf
	type (E | noE) #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ATTLIST KOR
	type (E | noE | subj | obj | AP) #IMPLIED
	ADDtype CDATA #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ATTLIST obj
	type (E | noE) #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ATTLIST akk
	type (E | noE) #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ATTLIST obl
	type (E | noE) #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ATTLIST prae
	type (E | noE) #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ATTLIST ADV
	type (E | noE) #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>
<!ATTLIST XX
	type (E | noE) #IMPLIED
	ID CDATA #IMPLIED
	change CDATA #IMPLIED
	viol CDATA #IMPLIED
	dir (V | R )  #IMPLIED
>


<!ELEMENT HV  (#PCDATA) >
<!ELEMENT VV  (#PCDATA) >
<!ELEMENT FV  (#PCDATA) >
<!ELEMENT PV  (#PCDATA) >
<!ELEMENT KV  (#PCDATA) >
<!ELEMENT MV  (#PCDATA) >
<!ELEMENT HMV  (#PCDATA) >
<!ELEMENT LASSEN  (#PCDATA) >
<!ELEMENT TUN  (#PCDATA) >
<!ELEMENT AcI  (#PCDATA) >
<!ELEMENT VP  (#PCDATA) >
<!ELEMENT RF  (#PCDATA) >
<!ELEMENT NGr  (#PCDATA) >
<!ELEMENT PGr  (#PCDATA) >
<!ELEMENT Phras  (#PCDATA) >
<!ELEMENT ADJGr  (#PCDATA) >
<!ELEMENT AP  (#PCDATA) >
<!ELEMENT KON  (#PCDATA) >
<!ELEMENT SUB  (#PCDATA) >
<!ELEMENT KOR  (#PCDATA) >
<!ELEMENT AD  (#PCDATA) >
<!ELEMENT FOK  (#PCDATA) >
<!ELEMENT VOR  (#PCDATA) >
<!ELEMENT IP  (#PCDATA) >
<!ELEMENT Inf  (#PCDATA) >
<!ELEMENT akk  (#PCDATA) >
<!ELEMENT obl  (#PCDATA) >
<!ELEMENT prae  (#PCDATA) >
<!ELEMENT ADV  (#PCDATA) >
<!ELEMENT XX  (#PCDATA) >

<!-- (C) International Organization for Standardization 1986
     Permission to copy in any form is granted for use with
     conforming SGML systems and applications as defined in
     ISO 8879, provided this notice is included in all copies.
-->
<!-- Character entity set. Typical invocation:
     <!ENTITY % HTMLlat1 PUBLIC
       "ISO 8879-1986//ENTITIES Added Latin 1//EN//XML">
-->
<!-- This version of the entity set can be used with any SGML document
     which uses ISO 8859-1 or ISO 10646 as its document character 
     set. This includes XML documents and ISO HTML documents. 
-->
 
    <!ENTITY Agrave  "&#192;" ><!-- capital A, grave accent -->
    <!ENTITY Aacute  "&#193;" ><!-- capital A, acute accent -->
    <!ENTITY Acirc   "&#194;" ><!-- capital A, circumflex accent -->
    <!ENTITY Atilde  "&#195;" ><!-- capital A, tilde -->
    <!ENTITY Auml    "&#196;" ><!-- capital A, dieresis or umlaut mark -->
    <!ENTITY Aring   "&#197;" ><!-- capital A, ring -->
    <!ENTITY AElig   "&#198;" ><!-- capital AE diphthong (ligature) -->
    <!ENTITY Ccedil  "&#199;" ><!-- capital C, cedilla -->
    <!ENTITY Egrave  "&#200;" ><!-- capital E, grave accent -->
    <!ENTITY Eacute  "&#201;" ><!-- capital E, acute accent -->
    <!ENTITY Ecirc   "&#202;" ><!-- capital E, circumflex accent -->
    <!ENTITY Euml    "&#203;" ><!-- capital E, dieresis or umlaut mark -->
    <!ENTITY Igrave  "&#204;" ><!-- capital I, grave accent -->
    <!ENTITY Iacute  "&#205;" ><!-- capital I, acute accent -->
    <!ENTITY Icirc   "&#206;" ><!-- capital I, circumflex accent -->
    <!ENTITY Iuml    "&#207;" ><!-- capital I, dieresis or umlaut mark -->
    <!ENTITY ETH     "&#208;" ><!-- capital Eth, Icelandic -->
    <!ENTITY Ntilde  "&#209;" ><!-- capital N, tilde -->
    <!ENTITY Ograve  "&#210;" ><!-- capital O, grave accent -->
    <!ENTITY Oacute  "&#211;" ><!-- capital O, acute accent -->
    <!ENTITY Ocirc   "&#212;" ><!-- capital O, circumflex accent -->
    <!ENTITY Otilde  "&#213;" ><!-- capital O, tilde -->
    <!ENTITY Ouml    "&#214;" ><!-- capital O, dieresis or umlaut mark -->
    <!ENTITY Oslash  "&#216;" ><!-- capital O, slash -->
    <!ENTITY Ugrave  "&#217;" ><!-- capital U, grave accent -->
    <!ENTITY Uacute  "&#218;" ><!-- capital U, acute accent -->
    <!ENTITY Ucirc   "&#219;" ><!-- capital U, circumflex accent -->
    <!ENTITY Uuml    "&#220;" ><!-- capital U, dieresis or umlaut mark -->
    <!ENTITY Yacute  "&#221;" ><!-- capital Y, acute accent -->
    <!ENTITY THORN   "&#222;" ><!-- capital THORN, Icelandic -->
    <!ENTITY szlig   "&#223;" ><!-- small sharp s, German (sz ligature) -->
    <!ENTITY agrave  "&#224;" ><!-- small a, grave accent -->   
    <!ENTITY aacute  "&#225;" ><!-- small a, acute accent -->
    <!ENTITY acirc   "&#226;" ><!-- small a, circumflex accent -->
    <!ENTITY atilde  "&#227;" ><!-- small a, tilde -->
    <!ENTITY auml    "&#228;" ><!-- small a, dieresis or umlaut mark -->
    <!ENTITY aring   "&#229;" ><!-- small a, ring -->
    <!ENTITY aelig   "&#230;" ><!-- small ae diphthong (ligature) -->
    <!ENTITY ccedil  "&#231;" ><!-- small c, cedilla -->
    <!ENTITY egrave  "&#232;" ><!-- small e, grave accent -->
    <!ENTITY eacute  "&#233;" ><!-- small e, acute accent -->
    <!ENTITY ecirc   "&#234;" ><!-- small e, circumflex accent -->
    <!ENTITY euml    "&#235;" ><!-- small e, dieresis or umlaut mark -->
    <!ENTITY igrave  "&#236;" ><!-- small i, grave accent -->
    <!ENTITY iacute  "&#237;" ><!-- small i, acute accent -->
    <!ENTITY icirc   "&#238;" ><!-- small i, circumflex accent -->
    <!ENTITY iuml    "&#239;" ><!-- small i, dieresis or umlaut mark -->
    <!ENTITY eth     "&#240;" ><!-- small eth, Icelandic -->
    <!ENTITY ntilde  "&#241;" ><!-- small n, tilde -->
    <!ENTITY ograve  "&#242;" ><!-- small o, grave accent -->
    <!ENTITY oacute  "&#243;" ><!-- small o, acute accent -->
    <!ENTITY ocirc   "&#244;" ><!-- small o, circumflex accent -->
    <!ENTITY otilde  "&#245;" ><!-- small o, tilde -->
    <!ENTITY ouml    "&#246;" ><!-- small o, dieresis or umlaut mark -->

    <!ENTITY oslash  "&#248;" ><!-- small o, slash -->
    <!ENTITY ugrave  "&#249;" ><!-- small u, grave accent -->
    <!ENTITY uacute  "&#250;" ><!-- small u, acute accent -->
    <!ENTITY ucirc   "&#251;" ><!-- small u, circumflex accent -->
    <!ENTITY uuml    "&#252;" ><!-- small u, dieresis or umlaut mark -->
    <!ENTITY yacute  "&#253;" ><!-- small y, acute accent -->
    <!ENTITY thorn   "&#254;" ><!-- small thorn, Icelandic -->
    <!ENTITY yuml    "&#255;" ><!-- small y, dieresis or umlaut mark -->

=== korpling/KajukModules/documents/xml/Bauernleben_bak.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE doc SYSTEM "documents/naehesprache.dtd">
<doc ID="T002">
	<pb n="38">
		<line n="1">
			<lb>
				<VOR>Im Jahr 1640 umb das Neue Jahr da</VOR>
				<praed>
					<V ID="Fin"><VV>kamen</VV></V>
				</praed> in das darmstÃ¤dische Land <subj>eine Armate schwedisch
			Volk.</subj></lb><!--hier line-->
		</line>
		<line n="2">
			<lb n="3000,2000">
				<VOR>Die</VOR>
				<praed>
					<V ID="Fin"><HV>hatte</HV></V>
				</praed>
				<praed>
					<V ID="PII"><VV>gefuhret</VV></V>
				</praed>
				<subj >ein Hertzog von Weinmar.</subj></lb>
		</line>
		

	</pb>

</doc>
